blank_issues_enabled: false

contact_links:

- name: Project/product documentation site
  url: https://your-url-goes-here/
  about: |-
    Project/product documentation can be found here.

- name: Corporate site
  url: https://your-url-goes-here/
  about: |-
    Our corporate website.
