blank_issues_enabled: false

contact_links:

- name: Community Slack workspace
  url: https://your-url-goes-here/
  about: |-
    Please ask and answer questions here.

- name: Your website name
  url: https://your-url-goes-here/
  about: |-
    Our website.
